### ISSUE TITLE
Invalid keys

### ISSUE THREAD

**Issue by ghost** [adamjace/mucholingo#6]
Hello, how would I end up adding my own data? e.g facebook page id, app secret etc? Tried to add in the config.js but that doesn't seem to work.

**Comment by adamjace** [comment]
You'll need a `.env` file in the root folder which contains your environment variables. check out the `env.example` as a baseline

**Comment by ghost** [comment]
Hey thanks for the quick reply! I followed the baseline of env.example and renamed it to config.env i inserted my port, but it still returns ` Error: Invalid configuration. Missing "port"
`
My .env looks like this `PORT="80",
FB_TOKEN=
FB_VERIFY=
FB_SECRET=
FB_PAGE_ID=
GOOGLE_KEY=
MIXPANEL_TOKEN=
REDIS_HOST=
REDIS_PORT=
REDIS_USER=
REDIS_PASSWORD=
SSL_KEY=
SSL_CERT=
SSL_CA=
`

**Comment by adamjace** [comment]
You'll need to name the file `.env` and also make sure you have done a `npm install` which includes a package call dotenv (which reads from the .env file and makes each key parsable by Nodejs)

The current bot in production requires all of these variables to contain values, so you'll need to have them populated with your own redis keys, google key, mixpanel token, ssl key etc.

As a workaround, what you can do though is either remove the check in config.js which validates the existence of each key (line 20) or remove each dependency from the code.  Removing these will require some code changes and the expected behaviour of the bot may change..

**Comment by ghost** [comment]
That's really odd tbh.. I figured it out later I would need to name my config file to .env, i did earlier `npm install` aswell, but i tried to re-install dotenv package in npm with `npm install dotenv -g` which said "Added 1 package" So i went ahead and tried to run my docker container with `docker-compose up` but it still says port value could not be found, although i have it. Would you mind looking the configuration for me via ssh? I could PM you somewhere.

**Comment by ghost** [comment]
Fixed that, had to do docker-compose build

**Comment by ghost** [comment]
Are you looking to do it hostable on heroku aswell?

**Comment by adamjace** [comment]
Glad you got it sorted 👍 

No plans at this stage for Heroku support
